// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  courseSidebar: [
    {
      type: 'category',
      label: 'Physical AI and Humanoid Robotics Course',
      items: [
        'course/intro',
        {
          type: 'category',
          label: 'Chapter 01: Foundations of Physical AI',
          items: [
            'chapters/foundations-of-physical-ai/index',
            'chapters/foundations-of-physical-ai/subchapter-1',
            'chapters/foundations-of-physical-ai/subchapter-2',
            'chapters/foundations-of-physical-ai/subchapter-3',
            'chapters/foundations-of-physical-ai/subchapter-4',
            'chapters/foundations-of-physical-ai/subchapter-5',
            'chapters/foundations-of-physical-ai/subchapter-6'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 02: Humanoid Robotics Architecture',
          items: [
            'chapters/humanoid-robotics-architecture/index',
            'chapters/humanoid-robotics-architecture/subchapter-1',
            'chapters/humanoid-robotics-architecture/subchapter-2',
            'chapters/humanoid-robotics-architecture/subchapter-3'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 03: Control Systems and Motion Planning',
          items: [
            'chapters/control-systems-motion-planning/index',
            'chapters/control-systems-motion-planning/subchapter-1',
            'chapters/control-systems-motion-planning/subchapter-2',
            'chapters/control-systems-motion-planning/subchapter-3'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 04: Perception and Environment Interaction',
          items: [
            'chapters/perception-environment-interaction/index',
            'chapters/perception-environment-interaction/subchapter-1',
            'chapters/perception-environment-interaction/subchapter-2'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 05: Learning and Adaptation',
          items: [
            'chapters/learning-adaptation/index',
            'chapters/learning-adaptation/subchapter-1'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 06: Human-Robot Interaction',
          items: [
            'chapters/human-robot-interaction/index',
            'chapters/human-robot-interaction/subchapter-1'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 07: Conclusion and Future Directions',
          items: [
            'chapters/conclusion/index'
          ]
        }
      ],
    },
  ],
};

module.exports = sidebars;